In [1]:
a=10
a

10

In [5]:
a=10
b=20
c=15
#print(a)
#print(b)
c

15

In [6]:
a=[11,22,33,44,55]
a

[11, 22, 33, 44, 55]

In [8]:
import numpy as n
score=n.array(a)
score

array([11, 22, 33, 44, 55])

In [9]:
d=n.mean(score)
d

np.float64(33.0)

In [10]:
print(n.max(score))

55


In [11]:
print(n.min(score))

11


In [16]:
f=n.zeros([2,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
print(n.ones([5,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
g=n.random.rand(2,1)
g

array([[0.33769487],
       [0.62498853]])

In [28]:
a=n.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a=n.array([1,2,3,4,5,6,7,8,9,10])
d=n.reshape(a,(10,1))
d

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [31]:
b=n.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
b=n.array([1,2,3,4,5,6,7,8,9,13])
c=b[1:5]
c

array([2, 3, 4, 5])

In [38]:
a=n.array([1,2,3])
b=n.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]


In [46]:
a=n.array([[2,4,5],[1,3,7]])
b=n.array([[1,2],
           [4,5],
           [1,8]])
c=n.dot(a,b)
c


array([[23, 64],
       [20, 73]])

In [47]:
mat=n.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
arr=n.array([9,6,5,8,1])
print(n.sort(arr))

[1 5 6 8 9]


In [51]:
a=n.array([1,2,4])
b=n.array([3,5,6])
print(n.concatenate((a,b)))

[1 2 4 3 5 6]


In [53]:
arr=n.array([1,2,2,3,4,4,5])
d=n.unique(arr)
d

array([1, 2, 3, 4, 5])

In [55]:

a=n.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
arr=n.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])